n1 = 10
n2= 15
print(n1 > n2)# en este caso n1 no es mayor que n2 asi que se imprime de forma (FALSE)}
print(n1 < n2)#ESTE SERIA VERDADERO
print(n1 <= n2)# n1 es menor o igual que n2 es (TRUE)
print(n1 >= n2)# n1 es mar o igual que n2 es (FALSE)
print(n2 == 15)# == significa que si el n2 es igual al numero que se pone (15) somo es verdadero se imprime TRUE

#ESTO SIRVE PARA CUANDO EL USUARIO QUIERE VERIFICAR SI LA TEMPERATURA ES MASYOR A CIERTO GRADO
#O PARA CUANDO EL USUARIO QUIERE VERIFICAR SI EL USUARIO ES MAYOR DE EDAD O MENOR
