resultado = input("Ingresa tu edad: ")#El input se pone cuando quiere que el ususario ingrese datos
print(type(resultado))#type significa que quiere que muestre en la impresion que clase de variabloe es si es texto(str), int, o float
#print(resultado + 22)||||#aqui nos va a dar error por que texto str y numero int no se mezcla de esta manera
numero = int(resultado)
print(numero + 2)# aqui si esta bien por que a el resultado se le asigno el (int) para que la impresion no vote el error y se puedas mezclar str con int.


TOTAL = input("pon el precio: ")
print(TOTAL)
numero = int(TOTAL)
print(numero + 10)
