puntaje = 10

if puntaje >= 95:
    print("aprovado con honores")#si(if) el puntaje(96), es mayor o igual a 95 tiene que aparecer ("aprovado con honores:")
elif puntaje >= 50:  #(elif) significa si "if" si if no es el resultado entonces elif si lo es hasta que quede el resultado correcto dependisno lo que digite el usuario
      print("aprovado")
else:#Else se usa parfa cuando no es correcto ninguna de las anteriores entonces simopre va a salir "reprovado"
      print("reprovado")

