                #0      #1     #2    #3      #4
lenguajes = ["python","ruby","php","java","javascript"]
print(lenguajes[1]) #el numero seleccionado [1] significa el elemento que quiere escoger de la lista, [1] seria el 2do de la lista por que en python empieza desde 0
lenguajes[1] = "Go" #esto se hace para que el elemento seleccionado se pueda cambiar el nombre
#tambien se puede poner numero negativo[-2] y ese -2 seria el penultimo de la lista por que lo que hace es ir de adelante hacia atras

print(lenguajes) 


